// Auto-generated by scripts/extract-codex-models.sh
// Run: bash scripts/extract-codex-models.sh
// Source: codex debug models (refreshed)

import type { CodexModelReasoningEffort } from "./codex-types";

export interface CodexModel {
  label: string;
  value: string;
  defaultReasoningEffort?: CodexModelReasoningEffort;
  supportedReasoningEfforts: CodexModelReasoningEffort[];
  supportsFastMode: boolean;
  upgradeTo?: string;
}

export const codexModels: CodexModel[] = [
  {
    label: "GPT-5.5",
    value: "gpt-5.5",
    defaultReasoningEffort: "xhigh",
    supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
    supportsFastMode: true,
  },
  {
    label: "GPT-5.4",
    value: "gpt-5.4",
    defaultReasoningEffort: "medium",
    supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
    supportsFastMode: true,
    upgradeTo: "gpt-5.5",
  },
  {
    label: "GPT-5.4-Mini",
    value: "gpt-5.4-mini",
    defaultReasoningEffort: "medium",
    supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
    supportsFastMode: false,
  },
];
