// Auto-generated by scripts/extract-cursor-models.sh
// Run: bash scripts/extract-cursor-models.sh

export interface CursorModel {
  label: string;
  value: string;
}

export const cursorModels: CursorModel[] = [
  { label: "Auto", value: "auto" },
  { label: "Composer 1.5", value: "composer-1.5" },
  { label: "Composer 1", value: "composer-1" },
  { label: "GPT 5.3 Codex", value: "gpt-5.3-codex" },
  { label: "GPT 5.3 Codex Low", value: "gpt-5.3-codex-low" },
  { label: "GPT 5.3 Codex High", value: "gpt-5.3-codex-high" },
  { label: "GPT 5.3 Codex Xhigh", value: "gpt-5.3-codex-xhigh" },
  { label: "GPT 5.3 Codex Fast", value: "gpt-5.3-codex-fast" },
  { label: "GPT 5.3 Codex Low Fast", value: "gpt-5.3-codex-low-fast" },
  { label: "GPT 5.3 Codex High Fast", value: "gpt-5.3-codex-high-fast" },
  { label: "GPT 5.3 Codex Xhigh Fast", value: "gpt-5.3-codex-xhigh-fast" },
  { label: "GPT 5.2", value: "gpt-5.2" },
  { label: "GPT 5.2 Codex", value: "gpt-5.2-codex" },
  { label: "GPT 5.2 Codex High", value: "gpt-5.2-codex-high" },
  { label: "GPT 5.2 Codex Low", value: "gpt-5.2-codex-low" },
  { label: "GPT 5.2 Codex Xhigh", value: "gpt-5.2-codex-xhigh" },
  { label: "GPT 5.2 Codex Fast", value: "gpt-5.2-codex-fast" },
  { label: "GPT 5.2 Codex High Fast", value: "gpt-5.2-codex-high-fast" },
  { label: "GPT 5.2 Codex Low Fast", value: "gpt-5.2-codex-low-fast" },
  { label: "GPT 5.2 Codex Xhigh Fast", value: "gpt-5.2-codex-xhigh-fast" },
  { label: "GPT 5.1 Codex Max", value: "gpt-5.1-codex-max" },
  { label: "GPT 5.1 Codex Max High", value: "gpt-5.1-codex-max-high" },
  { label: "Opus 4.6 Thinking", value: "opus-4.6-thinking" },
  { label: "GPT 5.2 High", value: "gpt-5.2-high" },
  { label: "Opus 4.6", value: "opus-4.6" },
  { label: "Opus 4.5", value: "opus-4.5" },
  { label: "Opus 4.5 Thinking", value: "opus-4.5-thinking" },
  { label: "Sonnet 4.6", value: "sonnet-4.6" },
  { label: "Sonnet 4.6 Thinking", value: "sonnet-4.6-thinking" },
  { label: "Sonnet 4.5", value: "sonnet-4.5" },
  { label: "Sonnet 4.5 Thinking", value: "sonnet-4.5-thinking" },
  { label: "GPT 5.1 High", value: "gpt-5.1-high" },
  { label: "Gemini 3.1 Pro", value: "gemini-3.1-pro" },
  { label: "Gemini 3 Pro", value: "gemini-3-pro" },
  { label: "Gemini 3 Flash", value: "gemini-3-flash" },
  { label: "GPT 5.1 Codex Mini", value: "gpt-5.1-codex-mini" },
  { label: "Grok", value: "grok" },
  { label: "Kimi K2.5", value: "kimi-k2.5" },
];
