#!/usr/bin/env bash
set -euo pipefail

# Run agent with an invalid model to get the list of available models
OUTPUT=$(agent --model "invalid model" 2>&1 || true)

# Extract everything after "Available models: "
MODELS_RAW=$(echo "$OUTPUT" | sed -n 's/.*Available models: //p')

if [ -z "$MODELS_RAW" ]; then
  echo "Error: Could not extract models from agent output" >&2
  echo "Output was: $OUTPUT" >&2
  exit 1
fi

# Target file
TARGET="src/shared/cursor-models.ts"

# Generate the TypeScript file
{
  echo "// Auto-generated by scripts/extract-cursor-models.sh"
  echo "// Run: bash scripts/extract-cursor-models.sh"
  echo ""
  echo "export interface CursorModel {"
  echo "  label: string;"
  echo "  value: string;"
  echo "}"
  echo ""
  echo "export const cursorModels: CursorModel[] = ["

  # Split on ", " and process each model
  IFS=', ' read -ra MODELS <<< "$MODELS_RAW"
  for model in "${MODELS[@]}"; do
    # Skip empty strings from splitting
    [ -z "$model" ] && continue

    # Convert kebab-case value to title-case label
    # e.g. gpt-5.3-codex-high -> GPT 5.3 Codex High
    label=$(echo "$model" | sed 's/-/ /g' | awk '{
      for (i=1; i<=NF; i++) {
        w = $i
        upper = toupper(w)
        # Keep known acronyms fully uppercase
        if (upper == "GPT" || upper == "AI" || upper == "API") {
          $i = upper
        } else if (w ~ /^[0-9]/) {
          # Numbers/versions stay as-is
          $i = w
        } else {
          $i = toupper(substr(w,1,1)) substr(w,2)
        }
      }
      print
    }')

    echo "  { label: \"$label\", value: \"$model\" },"
  done

  echo "];"
} > "$TARGET"

echo "Generated $TARGET with $(echo "$MODELS_RAW" | tr ',' '\n' | wc -l | tr -d ' ') models"
