#!/usr/bin/env bash
set -euo pipefail

# Fetch the list of available models from Codex CLI.
# Pass --bundled to use only the catalog shipped with the installed binary.
node - "$@" <<'NODE'
const { execFileSync } = require("node:child_process");
const { writeFileSync } = require("node:fs");

const cliArgs = process.argv.slice(2);
const forceBundled = cliArgs.includes("--bundled");

function readCatalog(args) {
  const output = execFileSync("codex", ["debug", "models", ...args], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  return JSON.parse(output);
}

let catalog;
let source;
try {
  catalog = readCatalog(forceBundled ? ["--bundled"] : []);
  source = forceBundled ? "bundled" : "refreshed";
} catch (error) {
  if (forceBundled) {
    throw error;
  }
  console.warn(
    "Could not refresh Codex model catalog; falling back to bundled catalog.",
  );
  catalog = readCatalog(["--bundled"]);
  source = "bundled fallback";
}

if (!catalog || !Array.isArray(catalog.models)) {
  throw new Error("Codex model catalog did not contain a models array.");
}

const models = catalog.models
  .filter((model) => model?.slug && model.visibility !== "hide")
  .sort((a, b) => {
    const priorityDelta = (a.priority ?? 999) - (b.priority ?? 999);
    if (priorityDelta !== 0) {
      return priorityDelta;
    }
    return String(a.slug).localeCompare(String(b.slug), undefined, {
      numeric: true,
      sensitivity: "base",
    });
  })
  .map((model) => ({
    label: model.display_name || model.slug,
    value: model.slug,
    defaultReasoningEffort: model.default_reasoning_level,
    supportedReasoningEfforts: (model.supported_reasoning_levels ?? [])
      .map((level) => level?.effort)
      .filter(Boolean),
    supportsFastMode:
      model.additional_speed_tiers?.includes("fast") ||
      model.service_tiers?.some((tier) => tier?.id === "priority") ||
      false,
    upgradeTo: model.upgrade?.model,
  }));

if (models.length === 0) {
  throw new Error("Codex model catalog did not contain any visible models.");
}

const target = "src/shared/codex-models.ts";
const body = [
  "// Auto-generated by scripts/extract-codex-models.sh",
  "// Run: bash scripts/extract-codex-models.sh",
  `// Source: codex debug models (${source})`,
  "",
  'import type { CodexModelReasoningEffort } from "./codex-types";',
  "",
  "export interface CodexModel {",
  "  label: string;",
  "  value: string;",
  "  defaultReasoningEffort?: CodexModelReasoningEffort;",
  "  supportedReasoningEfforts: CodexModelReasoningEffort[];",
  "  supportsFastMode: boolean;",
  "  upgradeTo?: string;",
  "}",
  "",
  `export const codexModels: CodexModel[] = ${JSON.stringify(models, null, 2)};`,
  "",
].join("\n");

writeFileSync(target, body);
console.log(`Generated ${target} with ${models.length} models from ${source} catalog`);
NODE
